***

## Artificial Neural Network ( ANN)

***


### Data Preprocessing

#### Importing libraries

In [1]:
import pandas as pd
import numpy as np 
import tensorflow as tf

#### Importing dataset

In [2]:
df = pd.read_csv("C:/Users/tze/OneDrive/ML_BOOTCAMP/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

#### features extraction

In [3]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

#### Features encoding

#### - Label encoding "Gender"

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
X[:, 2] = encoder.fit_transform(X[:, 2])

#### - One Hot Encoder for 'Geograpy'

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
transf = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(transf.fit_transform(X))

#### Splitting the dataset

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

#### Feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building ANN

#### Initializing the ANN

ANNs are created with <code>Tensorflow</code> library, specially with the <code>Keras</code> class and his method <code>Sequential()</code>

In [8]:
ann = tf.keras.models.Sequential()

#### Adding input layers and first hidden layers

With the <code>add()</code> method of <code>tf.keras</code> we're able to build layers whatever it is: input layers, output layers and even hidden ones.<br>
Also building layer requires another tensorflow method taking as main hyperparameters the number of layers and the activation function.<br>
In most of case the number of input layers is equal to the number of independant variables and the number of output layers is equal to the number of class of the dependant variables.

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#### Adding second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

### Training the ANNs 

#### Compiling the ANN

Here we are using binary cross-entropy as loss function because we're doing a binary classification.<br>
If we were doing non-binary classification we would use categorical cross-entropy as loss function.

Optimizer is an algorithm which update the NNs on purpose to upgrade weights and reduce loss function. Here we use the <code>adam optimizer</code> which is an adaptive optimise made by combination of others optimizers. 

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Fitting the model

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Epoch 1/50
Epoch 1/50
Epoch 1/50
235/235 [==============================] - 3s 4ms/step - loss: 0.6683 - accuracy: 0.6099
Epoch 2/50
Epoch 2/50
Epoch 2/50
Epoch 2/50
235/235 [==============================] - 1s 5ms/step - loss: 0.4845 - accuracy: 0.7949
Epoch 3/50
Epoch 3/50
Epoch 3/50
Epoch 3/50
235/235 [==============================] - 1s 6ms/step - loss: 0.4444 - accuracy: 0.8045
Epoch 4/50
Epoch 4/50
Epoch 4/50
Epoch 4/50
235/235 [==============================] - 2s 7ms/step - loss: 0.4234 - accuracy: 0.8151
Epoch 5/50
Epoch 5/50
Epoch 5/50
Epoch 5/50
235/235 [==============================] - 2s 6ms/step - loss: 0.4093 - accuracy: 0.8257
Epoch 6/50
Epoch 6/50
Epoch 6/50
Epoch 6/50
235/235 [==============================] - 1s 4ms/step - loss: 0.3975 - accuracy: 0.8320
Epoch 7/50
Epoch 7/50
Epoch 7/50
Epoch 7/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3871 - accuracy: 0.8385
Epoch 8/50
Epoch 8/50
Epoch 8/50
Epoch 8/50
235/235 [================

235/235 [==============================] - 1s 5ms/step - loss: 0.3441 - accuracy: 0.8571
Epoch 21/50
Epoch 21/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3432 - accuracy: 0.8584
Epoch 22/50
Epoch 22/50
Epoch 22/50
Epoch 22/50
235/235 [==============================] - 2s 6ms/step - loss: 0.3429 - accuracy: 0.8583
Epoch 23/50
Epoch 23/50
Epoch 23/50
Epoch 23/50
235/235 [==============================] - 2s 7ms/step - loss: 0.3423 - accuracy: 0.8595
Epoch 24/50
Epoch 24/50
Epoch 24/50
Epoch 24/50
235/235 [==============================] - 2s 7ms/step - loss: 0.3421 - accuracy: 0.8592
Epoch 25/50
Epoch 25/50
Epoch 25/50
Epoch 25/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3417 - accuracy: 0.8589
Epoch 26/50
Epoch 26/50
Epoch 26/50
Epoch 26/50
235/235 [==============================] - 2s 6ms/step - loss: 0.3409 - accuracy: 0.8603
Epoch 27/50
Epoch 27/50
Epoch 27/50
Epoch 27/50
235/235 [==============================] - 1s 6ms/step - loss: 0.

Epoch 40/50
Epoch 40/50
Epoch 40/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3377 - accuracy: 0.8627
Epoch 41/50
Epoch 41/50
Epoch 41/50
Epoch 41/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3373 - accuracy: 0.8620
Epoch 42/50
Epoch 42/50
Epoch 42/50
Epoch 42/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3368 - accuracy: 0.8624
Epoch 43/50
Epoch 43/50
Epoch 43/50
Epoch 43/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3370 - accuracy: 0.8605
Epoch 44/50
Epoch 44/50
Epoch 44/50
Epoch 44/50
235/235 [==============================] - 2s 7ms/step - loss: 0.3366 - accuracy: 0.8609
Epoch 45/50
Epoch 45/50
Epoch 45/50
Epoch 45/50
235/235 [==============================] - 2s 7ms/step - loss: 0.3364 - accuracy: 0.8615
Epoch 46/50
Epoch 46/50
Epoch 46/50
Epoch 46/50
235/235 [==============================] - 1s 6ms/step - loss: 0.3364 - accuracy: 0.8612
Epoch 47/50
Epoch 47/50
Epoch 47/50
Epoch 47/50
235/2

### Prediction and Performance Evaluation

#### Predicting the test set

In [16]:
y_pred = ann.predict(X_test) > 0.5

79/79 [==============================] - 0s 3ms/step


#### Confusion Matrix 

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
score = accuracy_score(y_test, y_pred)
print(matrix)
score

[[1918   85]
 [ 248  249]]


0.8668

[[1918   85]
 [ 248  249]]


0.8668

[[1918   85]
 [ 248  249]]


0.8668

[[1918   85]
 [ 248  249]]


0.8668

#### Predicting Single value

In [23]:
ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000.0, 2, 1, 1, 50000.0]])) > 0.5

1/1 [==============================] - 0s 52ms/step


array([[False]])

array([[False]])

array([[False]])

array([[False]])